### ISSUE TITLE
電子書籍版のチェリー本第2版とサンプルコードとの差異（11-2パターンマッチの基本）

### ISSUE THREAD

**Issue by haruguchi-yuma** [JunichiIto/ruby-book-codes-v2#1]
電子書籍版とサンプルコードに差異がありました。
サンプルコードの動作に支障がないことは確認したのですが、念のため報告しておきます:bow:

- サンプルコードをcloneした日: 2022年3月16日
- 該当箇所：「11-2パターンマッチの基本」の最後のコード(11.2.1の手前)　in節の`[]`の有無

## 電子書籍版
![image](https://user-images.githubusercontent.com/57053236/158566493-6a22715e-6d50-4546-b228-abe032c3898a.png)

## サンプルコード
```ruby
# これはcase文（case/when式）
case array
when [1, 2, 3]
  # ...
end

# これはパターンマッチ（case/in式）
case [1, 2, 3]
in a, b, c
  # ...
end
```

**Comment by JunichiIto** [comment]
@haruguchi-yuma  ご報告ありがとうございます！
ご指摘の通りなので修正しておきました😄

https://github.com/JunichiIto/ruby-book-codes-v2/commit/c26d475e73470fe540763b6e8bfdbe0e238d286a

**Comment by haruguchi-yuma** [comment]
@JunichiIto 
素早い対応ありがとうございます😄
