### ISSUE TITLE
チェリー本改定2版(書籍)とサンプルコードとの差異（column_05_04.rb）

### ISSUE THREAD

**Issue by SatoshiHaramura** [JunichiIto/ruby-book-codes-v2#2]
チェリー本改定2版(書籍)とサンプルコードにおいて、コードの差異がありましたので、以下の通りご報告させて頂きます🙏

`||`や`=`の位置が異なっておりました。

## チェリー本改定2版(書籍)
- 該当箇所：p.202 Column よく使われるイディオム(2)　||=を使った自己代入(nilガード) の 真ん中あたり

- 該当するコード

```
limit || limit = 10
```

## サンプルコード

- 該当するコード
https://github.com/JunichiIto/ruby-book-codes-v2/blob/c26d475e73470fe540763b6e8bfdbe0e238d286a/sample-codes/chapter_05/column_05_04.rb#L17

**Comment by JunichiIto** [comment]
ご報告ありがとうございます。修正しました！
https://github.com/JunichiIto/ruby-book-codes-v2/commit/23ea8430fb7ca48748403526b770f79cfbfff2ac
