### ISSUE TITLE
チェリー本改訂2版(書籍)とサンプルコードとの差異（11.4.1 入力データの取得）

### ISSUE THREAD

**Issue by aim2bpg** [JunichiIto/ruby-book-codes-v2#3]
書籍とサンプルコードで差異がありました。
書籍の説明との整合性を取るために、サンプルコード側を修正された方が良いと思います。
ご確認をお願いいたします🙏

## 書籍
```
require 'net/http'
require 'uri'
require 'json'
```

## サンプルコード
`log_formatter.rb`の`require 'json'`が一番上に来ており、書籍の順番と異なります。
https://github.com/JunichiIto/ruby-book-codes-v2/blob/c26d475e73470fe540763b6e8bfdbe0e238d286a/ruby-book/lib/log_formatter.rb#L1-L3

ちなみに、`code_11_04_01.rb`の`require`は、書籍と同じ並びでした。
https://github.com/JunichiIto/ruby-book-codes-v2/blob/c26d475e73470fe540763b6e8bfdbe0e238d286a/sample-codes/chapter_11/code_11_04_01.rb#L13-L15

https://github.com/JunichiIto/ruby-book-codes-v2/blob/c26d475e73470fe540763b6e8bfdbe0e238d286a/sample-codes/chapter_11/code_11_04_01.rb#L29-L31

**Comment by JunichiIto** [comment]
ご報告ありがとうございます。修正しました！
https://github.com/JunichiIto/ruby-book-codes-v2/commit/aa453ac34f00518934a72d2dd0c61ae818895b5d
