### ISSUE TITLE
サンプルコード内の誤字(code_08_04_03.rb)

### ISSUE THREAD

**Issue by hikarook94** [JunichiIto/ruby-book-codes-v2#4]
サンプルコード内で誤字と思われるものを見つけたので報告します🙇‍♂️
code_08_04_03.rbの35行目のブロックパラメータの区切り文字`|`が`¦`(ブロークンバー)になっているようで、実行するとエラーが出てしまいます。
ご確認の程よろしくお願いします🙏

## 該当箇所
https://github.com/JunichiIto/ruby-book-codes-v2/blob/c26d475e73470fe540763b6e8bfdbe0e238d286a/sample-codes/chapter_08/code_08_04_03.rb#L35

**Comment by JunichiIto** [comment]
ご報告ありがとうございます。修正しました！
https://github.com/JunichiIto/ruby-book-codes-v2/commit/7ba9c4c91a70ecd43fd5326ee71017a34030b2d1
