### ISSUE TITLE
チェリー本改訂2版(書籍)とサンプルコードとの差異（7.7.3〜7.7.5）

### ISSUE THREAD

**Issue by 10rayan** [JunichiIto/ruby-book-codes-v2#5]
書籍とこちらのサンプルコードで差異があったのでご報告します。
7.7.3〜7.7.5の間でサンプルコード内の記載内容にそれぞれズレが生じている様です。

|  書籍  |  サンプルコード  |
| ---- | ---- |
|  7.7.3  |  code_07_07_05.rb  |
|  7.7.4  |  code_07_07_03.rb  |
|  7.7.5  |  code_07_07_04.rb  |

**Comment by JunichiIto** [comment]
@10rayan ご報告ありがとうございます！たしかに間違ってそうですね。。。
のちほど確認＆修正しますのでしばらくお待ちください 🙏

**Comment by JunichiIto** [comment]
@10rayan こちら、修正完了しました。改めてご報告ありがとうございました！
