### ISSUE TITLE
サンプルコード内の誤字(code_11_02_00.rb)

### ISSUE THREAD

**Issue by gill876** [JunichiIto/ruby-book-codes-v2#6]
https://github.com/JunichiIto/ruby-book-codes-v2/blob/5b748f16842bde5811a0fdc04d6d862ce9f9db72/sample-codes/chapter_11/code_11_02_00.rb#L21C5-L21C41

書籍とこちらのサンプルコードで差異があったのでご報告します。
11.2の間でサンプルコード内の記載内容にそれぞれズレが生じている様です。

ご確認の程よろしくお願いします。

**Comment by JunichiIto** [comment]
@gill876 ご報告ありがとうございます＆返信遅くなってすいません。
仰るとおり、差異があったのでサンプルコードを修正しておきました。
他にも何かお気づきの点があればお気軽にご連絡ください！
よろしくお願いします。
